CREATE TYPE UserType as ENUM (
    'Admin', 'InventoryManager', 'Customer'
);

CREATE TABLE "User" (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(4) NOT NULL, --probs not permanent
    Type UserType NOT NULL
);

CREATE  TABLE Product (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    COST DOUBLE PRECISION NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL
);

CREATE TABLE Cart (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES "User"(ID)
);

CREATE TABLE CartProducts (
    CartID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    PRIMARY KEY (CartID, ProductID),
    FOREIGN KEY (CartID) REFERENCES Cart(ID),
    FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

CREATE TABLE Orders (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    IsComplete BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (UserID) REFERENCES "User"(ID)
);

CREATE TABLE OrderProducts (
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (OrderID, ProductID),
    FOREIGN KEY (OrderID) REFERENCES Orders(ID),
    FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

drop table "User";
drop table Product;
drop table Cart;
drop table CartProducts;
drop table Orders;
drop table OrderProducts;
